#!/bin/bash

# use awk / sed to insert route to supplied navigator file and update navigator spec

set -e

[ -z "$1" ] && echo "missing first param PAGE" && exit 1
[ -z "$2" ] && echo "missing second param NAVFILE" && exit 1
[ -z "$3" ] && echo "missing third param SPECFILE" && exit 1

PAGE=$1
NAVFILE=$2
SPECFILE=$3
INDEX=$4

tmpfile=$(mktemp)
echo "$tmpfile"

echo "updating navigator"

if [ -z "$INDEX" ]; then
  awk "/[ ]*case _ => controllers.routes.UnauthorisedController.onPageLoad\(\)$/{ print \"    case $PAGE(srn) => controllers.routes.UnauthorisedController.onPageLoad()\"; print \"\"}1" RS="\n" FS="\n" "$NAVFILE" > "$tmpfile"
else
  awk "/[ ]*case _ => controllers.routes.UnauthorisedController.onPageLoad\(\)$/{ print \"    case $PAGE(srn, index) => controllers.routes.UnauthorisedController.onPageLoad()\"; print \"\"}1" RS="\n" FS="\n" "$NAVFILE" > "$tmpfile"
fi
cat "$tmpfile"
cp "$tmpfile" "$NAVFILE"
rm "$tmpfile"

tmpfile=$(mktemp)
echo "$tmpfile"

echo "updating navigator spec"

if [ -z "$INDEX" ]; then
  echo "TODO no index, skipping test"
else
sed "\$s/\(}\)/\n  \"$PAGE\" - {\n"\
"    act.like(\n"\
"      normalmode\n"\
"      .navigateToWithIndex(\n"\
"        index,\n"\
"        $PAGE,\n"\
"        (srn, index: Max5000, _) => controllers.routes.UnauthorisedController.onPageLoad()\n"\
"      )\n"\
"      .withName(\"go from $PAGE to ??? page\")\n"\
"    )\n"\
"  }\n\1/" "$SPECFILE" > "$tmpfile"
cat "$tmpfile"
cp "$tmpfile" "$SPECFILE"
rm "$tmpfile"
fi
